export const REGS_ALL = 1;
export const REGS_ALE = 2;
export const REG_A = 3;
export const REG_B = 4;
export const REG_L = 5;
export const REG_H = 6;
export const REG_BA = 7;
export const REG_HL = 8;
export const REG_IX = 9;
export const REG_IY = 10;
export const REG_NB = 11;
export const REG_BR = 12;
export const REG_EP = 13;
export const REG_IP = 14;
export const REG_XP = 15;
export const REG_YP = 16;
export const REG_SC = 17;
export const REG_SP = 18;
export const REG_PC = 19;
export const MEM_ABS16 = 20;
export const MEM_HL = 21;
export const MEM_IX = 22;
export const MEM_IY = 23;
export const MEM_SP_DISP = 24;
export const MEM_IX_DISP = 25;
export const MEM_IY_DISP = 26;
export const MEM_IX_OFF = 27;
export const MEM_IY_OFF = 28;
export const MEM_BR = 29;
export const MEM_VECTOR = 30;
export const REL_8 = 31;
export const REL_16 = 32;
export const IMM_8 = 33;
export const IMM_16 = 34;

export const CONDITION_NONE = 1;
export const CONDITION_LESS_THAN = 2;
export const CONDITION_LESS_EQUAL = 3;
export const CONDITION_GREATER_THAN = 4;
export const CONDITION_GREATER_EQUAL = 5;
export const CONDITION_OVERFLOW = 6;
export const CONDITION_NOT_OVERFLOW = 7;
export const CONDITION_POSITIVE = 8;
export const CONDITION_MINUS = 9;
export const CONDITION_CARRY = 10;
export const CONDITION_NOT_CARRY = 11;
export const CONDITION_ZERO = 12;
export const CONDITION_NOT_ZERO = 13;
export const CONDITION_SPECIAL_FLAG_0 = 14;
export const CONDITION_SPECIAL_FLAG_1 = 15;
export const CONDITION_SPECIAL_FLAG_2 = 16;
export const CONDITION_SPECIAL_FLAG_3 = 17;
export const CONDITION_NOT_SPECIAL_FLAG_0 = 18;
export const CONDITION_NOT_SPECIAL_FLAG_1 = 19;
export const CONDITION_NOT_SPECIAL_FLAG_2 = 20;
export const CONDITION_NOT_SPECIAL_FLAG_3 = 21;

export const INSTRUCTION_TABLE =
[
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, REG_A ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_BR ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_ABS16 ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY ] },
	{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, REG_A ] },
	{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_BR ] },
	{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_ABS16 ] },
	{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX ] },
	{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, REG_A ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, MEM_BR ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, MEM_ABS16 ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY ] },
	{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, REG_A ] },
	{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_BR ] },
	{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_ABS16 ] },
	{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX ] },
	{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, REG_A ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, MEM_BR ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, MEM_ABS16 ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, REG_A ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_BR ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_ABS16 ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, REG_A ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, MEM_BR ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, MEM_ABS16 ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, REG_A ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_BR ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_ABS16 ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_A ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_L ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_H ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_BR ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, REG_A ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, REG_B ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, REG_L ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, REG_H ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, MEM_BR ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, MEM_HL ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, MEM_IX ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, MEM_IY ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, REG_A ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, REG_B ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, REG_L ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, REG_H ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, MEM_BR ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, MEM_HL ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, MEM_IX ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, MEM_IY ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, REG_A ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, REG_B ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, REG_L ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, REG_H ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, MEM_BR ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, MEM_HL ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, MEM_IX ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, MEM_IY ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, REG_A ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, REG_B ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, REG_L ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, REG_H ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, MEM_BR ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, MEM_HL ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, MEM_IX ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, MEM_IY ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_A ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_B ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_L ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_H ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_BR ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_HL ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, REG_A ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, REG_B ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, REG_L ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, REG_H ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, MEM_BR ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, MEM_HL ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, MEM_IX ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, MEM_IY ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_BR, REG_A ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_BR, REG_B ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_BR, REG_L ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_BR, REG_H ] },
	null,
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_BR, MEM_HL ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_BR, MEM_IX ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_BR, MEM_IY ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_A ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_B ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_L ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_H ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_BR ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_SP ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_A ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_B ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_L ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_H ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_BR ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_SP ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_BA ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_HL ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_IX ] },
	{ "op": "INC", "condition": CONDITION_NONE, "args": [ REG_IY ] },
	{ "op": "BIT", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "BIT", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
	{ "op": "BIT", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "BIT", "condition": CONDITION_NONE, "args": [ REG_B, IMM_8 ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_BA ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_HL ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_IX ] },
	{ "op": "DEC", "condition": CONDITION_NONE, "args": [ REG_IY ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_SC, IMM_8 ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_SC, IMM_8 ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_SC, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_SC, IMM_8 ] },
	{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_BA ] },
	{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_HL ] },
	{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_IX ] },
	{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_IY ] },
	{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_BR ] },
	{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_EP ] },
	{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_IP ] },
	{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_SC ] },
	{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_BA ] },
	{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_HL ] },
	{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_IX ] },
	{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_IY ] },
	{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_BR ] },
	{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_EP ] },
	{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_IP ] },
	{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_SC ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BR, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, MEM_ABS16 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, MEM_ABS16 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, MEM_ABS16 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, MEM_ABS16 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_ABS16, REG_BA ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_ABS16, REG_HL ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_ABS16, REG_IX ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_ABS16, REG_IY ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_BA, IMM_16 ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_HL, IMM_16 ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_IX, IMM_16 ] },
	{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_IY, IMM_16 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, IMM_16 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, IMM_16 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, IMM_16 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, IMM_16 ] },
	{ "op": "EX", "condition": CONDITION_NONE, "args": [ REG_BA, REG_HL ] },
	{ "op": "EX", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IX ] },
	{ "op": "EX", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IY ] },
	{ "op": "EX", "condition": CONDITION_NONE, "args": [ REG_BA, REG_SP ] },
	{ "op": "EX", "condition": CONDITION_NONE, "args": [ REG_A, REG_B ] },
	{ "op": "EX", "condition": CONDITION_NONE, "args": [ REG_A, MEM_HL ] },
	[
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_DISP ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_DISP ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_OFF ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_OFF ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_A ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_DISP ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_DISP ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_OFF ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_OFF ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_A ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_DISP ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_DISP ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_OFF ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_OFF ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_A ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_DISP ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_DISP ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_OFF ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_OFF ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_A ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_DISP ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_DISP ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_OFF ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_OFF ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_A ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_DISP ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_DISP ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_OFF ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_OFF ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_A ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_DISP ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_DISP ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_OFF ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_OFF ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_A ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_DISP ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_DISP ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_OFF ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_OFF ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_A ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ MEM_HL, IMM_8 ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IX_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_IY_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX_DISP, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY_DISP, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX_OFF, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY_OFF, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, MEM_IX_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, MEM_IY_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, MEM_IX_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, MEM_IY_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX_DISP, REG_B ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY_DISP, REG_B ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX_OFF, REG_B ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY_OFF, REG_B ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, MEM_IX_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, MEM_IY_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, MEM_IX_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, MEM_IY_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX_DISP, REG_L ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY_DISP, REG_L ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX_OFF, REG_L ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY_OFF, REG_L ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, MEM_IX_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, MEM_IY_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, MEM_IX_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, MEM_IY_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX_DISP, REG_H ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY_DISP, REG_H ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX_OFF, REG_H ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY_OFF, REG_H ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IX_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, MEM_IY_OFF ] },
		null,
		null,
		null,
		null,
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, MEM_IX_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, MEM_IY_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, MEM_IX_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, MEM_IY_OFF ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, MEM_IX_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, MEM_IY_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, MEM_IX_OFF ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, MEM_IY_OFF ] },
		null,
		null,
		null,
		null,
		{ "op": "SLA", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "SLA", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "SLA", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "SLA", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "SLL", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "SLL", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "SLL", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "SLL", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "SRA", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "SRA", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "SRA", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "SRA", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "SRL", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "SRL", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "SRL", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "SRL", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "RL", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "RL", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "RL", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "RL", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "RLC", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "RLC", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "RLC", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "RLC", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "RR", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "RR", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "RR", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "RR", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "RRC", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "RRC", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "RRC", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "RRC", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "CPL", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "CPL", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "CPL", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "CPL", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "NEG", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "NEG", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "NEG", "condition": CONDITION_NONE, "args": [ MEM_BR ] },
		{ "op": "NEG", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
		{ "op": "SEP", "condition": CONDITION_NONE, "args": [  ] },
		null,
		null,
		null,
		null,
		null,
		{ "op": "HALT", "condition": CONDITION_NONE, "args": [  ] },
		{ "op": "SLP", "condition": CONDITION_NONE, "args": [  ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_B, IMM_8 ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_L, IMM_8 ] },
		{ "op": "AND", "condition": CONDITION_NONE, "args": [ REG_H, IMM_8 ] },
		null,
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_B, IMM_8 ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_L, IMM_8 ] },
		{ "op": "OR", "condition": CONDITION_NONE, "args": [ REG_H, IMM_8 ] },
		null,
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_B, IMM_8 ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_L, IMM_8 ] },
		{ "op": "XOR", "condition": CONDITION_NONE, "args": [ REG_H, IMM_8 ] },
		null,
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_B, IMM_8 ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_L, IMM_8 ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_H, IMM_8 ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_BR, IMM_8 ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_BR ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_SC ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BR, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_SC, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_NB, IMM_8 ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_EP, IMM_8 ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_XP, IMM_8 ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_YP, IMM_8 ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_NB ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_EP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_XP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, REG_YP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_NB, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_EP, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_XP, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_YP, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_A, MEM_ABS16 ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_B, MEM_ABS16 ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_L, MEM_ABS16 ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_H, MEM_ABS16 ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_ABS16, REG_A ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_ABS16, REG_B ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_ABS16, REG_L ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_ABS16, REG_H ] },
		{ "op": "MLT", "condition": CONDITION_NONE, "args": [  ] },
		{ "op": "DIV", "condition": CONDITION_NONE, "args": [  ] },
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "JRS", "condition": CONDITION_LESS_THAN, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_LESS_EQUAL, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_GREATER_THAN, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_GREATER_EQUAL, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_OVERFLOW, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_NOT_OVERFLOW, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_POSITIVE, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_MINUS, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_SPECIAL_FLAG_0, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_SPECIAL_FLAG_1, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_SPECIAL_FLAG_2, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_SPECIAL_FLAG_3, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_NOT_SPECIAL_FLAG_0, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_NOT_SPECIAL_FLAG_1, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_NOT_SPECIAL_FLAG_2, "args": [ REL_8 ] },
		{ "op": "JRS", "condition": CONDITION_NOT_SPECIAL_FLAG_3, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_LESS_THAN, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_LESS_EQUAL, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_GREATER_THAN, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_GREATER_EQUAL, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_OVERFLOW, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_NOT_OVERFLOW, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_POSITIVE, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_MINUS, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_SPECIAL_FLAG_0, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_SPECIAL_FLAG_1, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_SPECIAL_FLAG_2, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_SPECIAL_FLAG_3, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_NOT_SPECIAL_FLAG_0, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_NOT_SPECIAL_FLAG_1, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_NOT_SPECIAL_FLAG_2, "args": [ REL_8 ] },
		{ "op": "CARS", "condition": CONDITION_NOT_SPECIAL_FLAG_3, "args": [ REL_8 ] }
	],
	[
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_BA ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_HL ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IX ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IY ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_BA, REG_BA ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_BA, REG_HL ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IX ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IY ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_BA, REG_BA ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_BA, REG_HL ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IX ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IY ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_BA, REG_BA ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_BA, REG_HL ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IX ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IY ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_BA, REG_BA ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_BA, REG_HL ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IX ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IY ] },
		null,
		null,
		null,
		null,
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_BA ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_HL ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IX ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IY ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_HL, REG_BA ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_HL, REG_HL ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IX ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IY ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_HL, REG_BA ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_HL, REG_HL ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IX ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IY ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_HL, REG_BA ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_HL, REG_HL ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IX ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IY ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_HL, REG_BA ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_HL, REG_HL ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IX ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IY ] },
		null,
		null,
		null,
		null,
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_IX, REG_BA ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_IX, REG_HL ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_IY, REG_BA ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_IY, REG_HL ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_SP, REG_BA ] },
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_SP, REG_HL ] },
		null,
		null,
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_IX, REG_BA ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_IX, REG_HL ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_IY, REG_BA ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_IY, REG_HL ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_SP, REG_BA ] },
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_SP, REG_HL ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_SP, REG_BA ] },
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_SP, REG_HL ] },
		null,
		null,
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_BA, IMM_16 ] },
		{ "op": "ADC", "condition": CONDITION_NONE, "args": [ REG_HL, IMM_16 ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_BA, IMM_16 ] },
		{ "op": "SBC", "condition": CONDITION_NONE, "args": [ REG_HL, IMM_16 ] },
		null,
		null,
		null,
		null,
		{ "op": "ADD", "condition": CONDITION_NONE, "args": [ REG_SP, IMM_16 ] },
		null,
		{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_SP, IMM_16 ] },
		null,
		{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_SP, IMM_16 ] },
		null,
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_SP, IMM_16 ] },
		null,
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, MEM_SP_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, MEM_SP_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, MEM_SP_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, MEM_SP_DISP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_SP_DISP, REG_BA ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_SP_DISP, REG_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_SP_DISP, REG_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_SP_DISP, REG_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_SP, MEM_ABS16 ] },
		null,
		null,
		null,
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_ABS16, REG_SP ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_L ] },
		{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REG_H ] },
		{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_A ] },
		{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_B ] },
		{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_L ] },
		{ "op": "POP", "condition": CONDITION_NONE, "args": [ REG_H ] },
		{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REGS_ALL ] },
		{ "op": "PUSH", "condition": CONDITION_NONE, "args": [ REGS_ALE ] },
		null,
		null,
		{ "op": "POP", "condition": CONDITION_NONE, "args": [ REGS_ALL ] },
		{ "op": "POP", "condition": CONDITION_NONE, "args": [ REGS_ALE ] },
		null,
		null,
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, MEM_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, MEM_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, MEM_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, MEM_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_BA ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_HL, REG_IY ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, MEM_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, MEM_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, MEM_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, MEM_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, REG_BA ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, REG_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, REG_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IX, REG_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, MEM_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, MEM_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, MEM_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, MEM_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, REG_BA ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, REG_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, REG_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_IY, REG_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_BA ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_BA ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, REG_BA ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, REG_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, REG_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, REG_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, REG_BA ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, REG_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, REG_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, REG_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_SP, REG_BA ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_SP, REG_HL ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_SP, REG_IX ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_SP, REG_IY ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_SP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_HL, REG_PC ] },
		null,
		null,
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_SP ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_BA, REG_PC ] },
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IX, REG_SP ] },
		null,
		null,
		null,
		{ "op": "LD", "condition": CONDITION_NONE, "args": [ REG_IY, REG_SP ] },
		null
	],
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_BA, IMM_16 ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_HL, IMM_16 ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_IX, IMM_16 ] },
	{ "op": "SUB", "condition": CONDITION_NONE, "args": [ REG_IY, IMM_16 ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_BA, IMM_16 ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_HL, IMM_16 ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_IX, IMM_16 ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ REG_IY, IMM_16 ] },
	{ "op": "AND", "condition": CONDITION_NONE, "args": [ MEM_BR, IMM_8 ] },
	{ "op": "OR", "condition": CONDITION_NONE, "args": [ MEM_BR, IMM_8 ] },
	{ "op": "XOR", "condition": CONDITION_NONE, "args": [ MEM_BR, IMM_8 ] },
	{ "op": "CP", "condition": CONDITION_NONE, "args": [ MEM_BR, IMM_8 ] },
	{ "op": "BIT", "condition": CONDITION_NONE, "args": [ MEM_BR, IMM_8 ] },
	{ "op": "LD", "condition": CONDITION_NONE, "args": [ MEM_BR, IMM_8 ] },
	{ "op": "PACK", "condition": CONDITION_NONE, "args": [  ] },
	{ "op": "UPCK", "condition": CONDITION_NONE, "args": [  ] },
	{ "op": "CARS", "condition": CONDITION_CARRY, "args": [ REL_8 ] },
	{ "op": "CARS", "condition": CONDITION_NOT_CARRY, "args": [ REL_8 ] },
	{ "op": "CARS", "condition": CONDITION_ZERO, "args": [ REL_8 ] },
	{ "op": "CARS", "condition": CONDITION_NOT_ZERO, "args": [ REL_8 ] },
	{ "op": "JRS", "condition": CONDITION_CARRY, "args": [ REL_8 ] },
	{ "op": "JRS", "condition": CONDITION_NOT_CARRY, "args": [ REL_8 ] },
	{ "op": "JRS", "condition": CONDITION_ZERO, "args": [ REL_8 ] },
	{ "op": "JRS", "condition": CONDITION_NOT_ZERO, "args": [ REL_8 ] },
	{ "op": "CARL", "condition": CONDITION_CARRY, "args": [ REL_16 ] },
	{ "op": "CARL", "condition": CONDITION_NOT_CARRY, "args": [ REL_16 ] },
	{ "op": "CARL", "condition": CONDITION_ZERO, "args": [ REL_16 ] },
	{ "op": "CARL", "condition": CONDITION_NOT_ZERO, "args": [ REL_16 ] },
	{ "op": "JRL", "condition": CONDITION_CARRY, "args": [ REL_16 ] },
	{ "op": "JRL", "condition": CONDITION_NOT_CARRY, "args": [ REL_16 ] },
	{ "op": "JRL", "condition": CONDITION_ZERO, "args": [ REL_16 ] },
	{ "op": "JRL", "condition": CONDITION_NOT_ZERO, "args": [ REL_16 ] },
	{ "op": "CARS", "condition": CONDITION_NONE, "args": [ REL_8 ] },
	{ "op": "JRS", "condition": CONDITION_NONE, "args": [ REL_8 ] },
	{ "op": "CARL", "condition": CONDITION_NONE, "args": [ REL_16 ] },
	{ "op": "JRL", "condition": CONDITION_NONE, "args": [ REL_16 ] },
	{ "op": "JP", "condition": CONDITION_NONE, "args": [ REG_HL ] },
	{ "op": "DJR", "condition": CONDITION_NOT_ZERO, "args": [ REL_8 ] },
	{ "op": "SWAP", "condition": CONDITION_NONE, "args": [ REG_A ] },
	{ "op": "SWAP", "condition": CONDITION_NONE, "args": [ MEM_HL ] },
	{ "op": "RET", "condition": CONDITION_NONE, "args": [  ] },
	{ "op": "RETE", "condition": CONDITION_NONE, "args": [  ] },
	{ "op": "RETS", "condition": CONDITION_NONE, "args": [  ] },
	{ "op": "CALL", "condition": CONDITION_NONE, "args": [ MEM_ABS16 ] },
	{ "op": "INT", "condition": CONDITION_NONE, "args": [ MEM_VECTOR ] },
	{ "op": "JP", "condition": CONDITION_NONE, "args": [ MEM_VECTOR ] },
	null,
	{ "op": "NOP", "condition": CONDITION_NONE, "args": [  ] }
];
