export enum Argument {
    REGS_ALL,
	REGS_ALE,
	REG_A,
	REG_B,
	REG_L,
	REG_H,
	REG_BA,
	REG_HL,
	REG_IX,
	REG_IY,
	REG_NB,
	REG_BR,
	REG_EP,
	REG_IP,
	REG_XP,
	REG_YP,
	REG_SC,
	REG_SP,
	REG_PC,
	MEM_ABS16,
	MEM_HL,
	MEM_IX,
	MEM_IY,
	MEM_SP_DISP,
	MEM_IX_DISP,
	MEM_IY_DISP,
	MEM_IX_OFF,
	MEM_IY_OFF,
	MEM_BR,
	MEM_VECTOR,
	REL_8,
	REL_16,
	IMM_8,
	IMM_16 
};
export enum Condition {
    NONE,
	LESS_THAN,
	LESS_EQUAL,
	GREATER_THAN,
	GREATER_EQUAL,
	OVERFLOW,
	NOT_OVERFLOW,
	POSITIVE,
	MINUS,
	CARRY,
	NOT_CARRY,
	ZERO,
	NOT_ZERO,
	SPECIAL_FLAG_0,
	SPECIAL_FLAG_1,
	SPECIAL_FLAG_2,
	SPECIAL_FLAG_3,
	NOT_SPECIAL_FLAG_0,
	NOT_SPECIAL_FLAG_1,
	NOT_SPECIAL_FLAG_2,
	NOT_SPECIAL_FLAG_3 
};
export const InstructionTable = [
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_A ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_BR ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_ABS16 ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY ] },
	{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_A ] },
	{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_BR ] },
	{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_ABS16 ] },
	{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX ] },
	{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_A ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_BR ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_ABS16 ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY ] },
	{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_A ] },
	{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_BR ] },
	{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_ABS16 ] },
	{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX ] },
	{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_A ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_BR ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_ABS16 ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_A ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_BR ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_ABS16 ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_A ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_BR ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_ABS16 ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_A ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_BR ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_ABS16 ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_A ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_L ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_H ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_BR ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.REG_A ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.REG_B ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.REG_L ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.REG_H ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.MEM_BR ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.MEM_HL ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.MEM_IX ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.MEM_IY ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.REG_A ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.REG_B ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.REG_L ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.REG_H ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.MEM_BR ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.MEM_HL ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.MEM_IX ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.MEM_IY ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.REG_A ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.REG_B ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.REG_L ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.REG_H ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.MEM_BR ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.MEM_HL ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.MEM_IX ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.MEM_IY ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.REG_A ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.REG_B ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.REG_L ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.REG_H ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.MEM_BR ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.MEM_HL ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.MEM_IX ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.MEM_IY ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_A ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_B ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_L ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_H ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_BR ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_HL ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.REG_A ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.REG_B ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.REG_L ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.REG_H ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.MEM_BR ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.MEM_HL ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.MEM_IX ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.MEM_IY ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.REG_A ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.REG_B ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.REG_L ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.REG_H ] },
	null,
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.MEM_HL ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.MEM_IX ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.MEM_IY ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_L ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_H ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_BR ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_SP ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_L ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_H ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_BR ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_SP ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_BA ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_HL ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_IX ] },
	{ "op": "INC", "condition": Condition.NONE, "args": [ Argument.REG_IY ] },
	{ "op": "BIT", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "BIT", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
	{ "op": "BIT", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "BIT", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.IMM_8 ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_BA ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_HL ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_IX ] },
	{ "op": "DEC", "condition": Condition.NONE, "args": [ Argument.REG_IY ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_SC, Argument.IMM_8 ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_SC, Argument.IMM_8 ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_SC, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_SC, Argument.IMM_8 ] },
	{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_BA ] },
	{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_HL ] },
	{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_IX ] },
	{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_IY ] },
	{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_BR ] },
	{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_EP ] },
	{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_IP ] },
	{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_SC ] },
	{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_BA ] },
	{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_HL ] },
	{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_IX ] },
	{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_IY ] },
	{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_BR ] },
	{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_EP ] },
	{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_IP ] },
	{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_SC ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BR, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.MEM_ABS16 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.MEM_ABS16 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.MEM_ABS16 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.MEM_ABS16 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16, Argument.REG_BA ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16, Argument.REG_HL ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16, Argument.REG_IX ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16, Argument.REG_IY ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.IMM_16 ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.IMM_16 ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.IMM_16 ] },
	{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.IMM_16 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.IMM_16 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.IMM_16 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.IMM_16 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.IMM_16 ] },
	{ "op": "EX", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_HL ] },
	{ "op": "EX", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IX ] },
	{ "op": "EX", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IY ] },
	{ "op": "EX", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_SP ] },
	{ "op": "EX", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_B ] },
	{ "op": "EX", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_HL ] },
	[
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_DISP ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_DISP ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_OFF ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_OFF ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_A ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_DISP ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_DISP ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_OFF ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_OFF ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_A ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_DISP ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_DISP ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_OFF ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_OFF ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_A ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_DISP ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_DISP ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_OFF ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_OFF ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_A ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_DISP ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_DISP ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_OFF ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_OFF ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_A ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_DISP ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_DISP ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_OFF ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_OFF ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_A ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_DISP ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_DISP ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_OFF ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_OFF ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_A ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_DISP ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_DISP ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_OFF ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_OFF ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_A ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.IMM_8 ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IX_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_IY_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX_DISP, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY_DISP, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX_OFF, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY_OFF, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.MEM_IX_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.MEM_IY_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.MEM_IX_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.MEM_IY_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX_DISP, Argument.REG_B ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY_DISP, Argument.REG_B ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX_OFF, Argument.REG_B ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY_OFF, Argument.REG_B ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.MEM_IX_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.MEM_IY_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.MEM_IX_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.MEM_IY_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX_DISP, Argument.REG_L ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY_DISP, Argument.REG_L ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX_OFF, Argument.REG_L ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY_OFF, Argument.REG_L ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.MEM_IX_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.MEM_IY_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.MEM_IX_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.MEM_IY_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX_DISP, Argument.REG_H ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY_DISP, Argument.REG_H ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX_OFF, Argument.REG_H ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY_OFF, Argument.REG_H ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IX_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.MEM_IY_OFF ] },
		null,
		null,
		null,
		null,
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.MEM_IX_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.MEM_IY_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.MEM_IX_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.MEM_IY_OFF ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.MEM_IX_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.MEM_IY_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.MEM_IX_OFF ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.MEM_IY_OFF ] },
		null,
		null,
		null,
		null,
		{ "op": "SLA", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "SLA", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "SLA", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "SLA", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "SLL", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "SLL", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "SLL", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "SLL", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "SRA", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "SRA", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "SRA", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "SRA", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "SRL", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "SRL", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "SRL", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "SRL", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "RL", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "RL", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "RL", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "RL", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "RLC", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "RLC", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "RLC", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "RLC", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "RR", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "RR", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "RR", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "RR", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "RRC", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "RRC", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "RRC", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "RRC", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "CPL", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "CPL", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "CPL", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "CPL", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "NEG", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "NEG", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "NEG", "condition": Condition.NONE, "args": [ Argument.MEM_BR ] },
		{ "op": "NEG", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
		{ "op": "SEP", "condition": Condition.NONE, "args": [  ] },
		null,
		null,
		null,
		null,
		null,
		{ "op": "HALT", "condition": Condition.NONE, "args": [  ] },
		{ "op": "SLP", "condition": Condition.NONE, "args": [  ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.IMM_8 ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.IMM_8 ] },
		{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.IMM_8 ] },
		null,
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.IMM_8 ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.IMM_8 ] },
		{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.IMM_8 ] },
		null,
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.IMM_8 ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.IMM_8 ] },
		{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.IMM_8 ] },
		null,
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.IMM_8 ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.IMM_8 ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.IMM_8 ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_BR, Argument.IMM_8 ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_BR ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_SC ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BR, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_SC, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_NB, Argument.IMM_8 ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_EP, Argument.IMM_8 ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_XP, Argument.IMM_8 ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_YP, Argument.IMM_8 ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_NB ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_EP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_XP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.REG_YP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_NB, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_EP, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_XP, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_YP, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_A, Argument.MEM_ABS16 ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_B, Argument.MEM_ABS16 ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_L, Argument.MEM_ABS16 ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_H, Argument.MEM_ABS16 ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16, Argument.REG_A ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16, Argument.REG_B ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16, Argument.REG_L ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16, Argument.REG_H ] },
		{ "op": "MLT", "condition": Condition.NONE, "args": [  ] },
		{ "op": "DIV", "condition": Condition.NONE, "args": [  ] },
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "JRS", "condition": Condition.LESS_THAN, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.LESS_EQUAL, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.GREATER_THAN, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.GREATER_EQUAL, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.OVERFLOW, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.NOT_OVERFLOW, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.POSITIVE, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.MINUS, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.SPECIAL_FLAG_0, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.SPECIAL_FLAG_1, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.SPECIAL_FLAG_2, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.SPECIAL_FLAG_3, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.NOT_SPECIAL_FLAG_0, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.NOT_SPECIAL_FLAG_1, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.NOT_SPECIAL_FLAG_2, "args": [ Argument.REL_8 ] },
		{ "op": "JRS", "condition": Condition.NOT_SPECIAL_FLAG_3, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.LESS_THAN, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.LESS_EQUAL, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.GREATER_THAN, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.GREATER_EQUAL, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.OVERFLOW, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.NOT_OVERFLOW, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.POSITIVE, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.MINUS, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.SPECIAL_FLAG_0, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.SPECIAL_FLAG_1, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.SPECIAL_FLAG_2, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.SPECIAL_FLAG_3, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.NOT_SPECIAL_FLAG_0, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.NOT_SPECIAL_FLAG_1, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.NOT_SPECIAL_FLAG_2, "args": [ Argument.REL_8 ] },
		{ "op": "CARS", "condition": Condition.NOT_SPECIAL_FLAG_3, "args": [ Argument.REL_8 ] }
	],
	[
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_BA ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_HL ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IX ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IY ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_BA ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_HL ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IX ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IY ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_BA ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_HL ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IX ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IY ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_BA ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_HL ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IX ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IY ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_BA ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_HL ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IX ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IY ] },
		null,
		null,
		null,
		null,
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_BA ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_HL ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IX ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IY ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_BA ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_HL ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IX ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IY ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_BA ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_HL ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IX ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IY ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_BA ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_HL ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IX ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IY ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_BA ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_HL ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IX ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IY ] },
		null,
		null,
		null,
		null,
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.REG_BA ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.REG_HL ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.REG_BA ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.REG_HL ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_BA ] },
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_HL ] },
		null,
		null,
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.REG_BA ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.REG_HL ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.REG_BA ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.REG_HL ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_BA ] },
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_HL ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_BA ] },
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_HL ] },
		null,
		null,
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.IMM_16 ] },
		{ "op": "ADC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.IMM_16 ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.IMM_16 ] },
		{ "op": "SBC", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.IMM_16 ] },
		null,
		null,
		null,
		null,
		{ "op": "ADD", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.IMM_16 ] },
		null,
		{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.IMM_16 ] },
		null,
		{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.IMM_16 ] },
		null,
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.IMM_16 ] },
		null,
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.MEM_SP_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.MEM_SP_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.MEM_SP_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.MEM_SP_DISP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_SP_DISP, Argument.REG_BA ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_SP_DISP, Argument.REG_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_SP_DISP, Argument.REG_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_SP_DISP, Argument.REG_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.MEM_ABS16 ] },
		null,
		null,
		null,
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16, Argument.REG_SP ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_L ] },
		{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REG_H ] },
		{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
		{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_B ] },
		{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_L ] },
		{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REG_H ] },
		{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REGS_ALL ] },
		{ "op": "PUSH", "condition": Condition.NONE, "args": [ Argument.REGS_ALE ] },
		null,
		null,
		{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REGS_ALL ] },
		{ "op": "POP", "condition": Condition.NONE, "args": [ Argument.REGS_ALE ] },
		null,
		null,
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.MEM_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.MEM_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.MEM_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.MEM_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_BA ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_HL, Argument.REG_IY ] },
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.MEM_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.MEM_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.MEM_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.MEM_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.REG_BA ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.REG_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.REG_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IX, Argument.REG_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.MEM_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.MEM_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.MEM_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.MEM_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.REG_BA ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.REG_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.REG_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_IY, Argument.REG_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_BA ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_BA ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.REG_BA ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.REG_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.REG_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.REG_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.REG_BA ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.REG_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.REG_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.REG_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_BA ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_HL ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_IX ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_SP, Argument.REG_IY ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_SP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.REG_PC ] },
		null,
		null,
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_SP ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.REG_PC ] },
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.REG_SP ] },
		null,
		null,
		null,
		{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.REG_SP ] },
		null
	],
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.IMM_16 ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.IMM_16 ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.IMM_16 ] },
	{ "op": "SUB", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.IMM_16 ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_BA, Argument.IMM_16 ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_HL, Argument.IMM_16 ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_IX, Argument.IMM_16 ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.REG_IY, Argument.IMM_16 ] },
	{ "op": "AND", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.IMM_8 ] },
	{ "op": "OR", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.IMM_8 ] },
	{ "op": "XOR", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.IMM_8 ] },
	{ "op": "CP", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.IMM_8 ] },
	{ "op": "BIT", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.IMM_8 ] },
	{ "op": "LD", "condition": Condition.NONE, "args": [ Argument.MEM_BR, Argument.IMM_8 ] },
	{ "op": "PACK", "condition": Condition.NONE, "args": [  ] },
	{ "op": "UPCK", "condition": Condition.NONE, "args": [  ] },
	{ "op": "CARS", "condition": Condition.CARRY, "args": [ Argument.REL_8 ] },
	{ "op": "CARS", "condition": Condition.NOT_CARRY, "args": [ Argument.REL_8 ] },
	{ "op": "CARS", "condition": Condition.ZERO, "args": [ Argument.REL_8 ] },
	{ "op": "CARS", "condition": Condition.NOT_ZERO, "args": [ Argument.REL_8 ] },
	{ "op": "JRS", "condition": Condition.CARRY, "args": [ Argument.REL_8 ] },
	{ "op": "JRS", "condition": Condition.NOT_CARRY, "args": [ Argument.REL_8 ] },
	{ "op": "JRS", "condition": Condition.ZERO, "args": [ Argument.REL_8 ] },
	{ "op": "JRS", "condition": Condition.NOT_ZERO, "args": [ Argument.REL_8 ] },
	{ "op": "CARL", "condition": Condition.CARRY, "args": [ Argument.REL_16 ] },
	{ "op": "CARL", "condition": Condition.NOT_CARRY, "args": [ Argument.REL_16 ] },
	{ "op": "CARL", "condition": Condition.ZERO, "args": [ Argument.REL_16 ] },
	{ "op": "CARL", "condition": Condition.NOT_ZERO, "args": [ Argument.REL_16 ] },
	{ "op": "JRL", "condition": Condition.CARRY, "args": [ Argument.REL_16 ] },
	{ "op": "JRL", "condition": Condition.NOT_CARRY, "args": [ Argument.REL_16 ] },
	{ "op": "JRL", "condition": Condition.ZERO, "args": [ Argument.REL_16 ] },
	{ "op": "JRL", "condition": Condition.NOT_ZERO, "args": [ Argument.REL_16 ] },
	{ "op": "CARS", "condition": Condition.NONE, "args": [ Argument.REL_8 ] },
	{ "op": "JRS", "condition": Condition.NONE, "args": [ Argument.REL_8 ] },
	{ "op": "CARL", "condition": Condition.NONE, "args": [ Argument.REL_16 ] },
	{ "op": "JRL", "condition": Condition.NONE, "args": [ Argument.REL_16 ] },
	{ "op": "JP", "condition": Condition.NONE, "args": [ Argument.REG_HL ] },
	{ "op": "DJR", "condition": Condition.NOT_ZERO, "args": [ Argument.REL_8 ] },
	{ "op": "SWAP", "condition": Condition.NONE, "args": [ Argument.REG_A ] },
	{ "op": "SWAP", "condition": Condition.NONE, "args": [ Argument.MEM_HL ] },
	{ "op": "RET", "condition": Condition.NONE, "args": [  ] },
	{ "op": "RETE", "condition": Condition.NONE, "args": [  ] },
	{ "op": "RETS", "condition": Condition.NONE, "args": [  ] },
	{ "op": "CALL", "condition": Condition.NONE, "args": [ Argument.MEM_ABS16 ] },
	{ "op": "INT", "condition": Condition.NONE, "args": [ Argument.MEM_VECTOR ] },
	{ "op": "JP", "condition": Condition.NONE, "args": [ Argument.MEM_VECTOR ] },
	null,
	{ "op": "NOP", "condition": Condition.NONE, "args": [  ] }
];
